"""
Homepage for Payroll Process Automation Suite.

Displays:
- Executive dashboard metrics
- Module cards
- Overall workflow
- Future module placeholders
"""

from __future__ import annotations

import sys
from pathlib import Path

import streamlit as st

ROOT_DIR = Path(__file__).resolve().parents[1]

if str(ROOT_DIR) not in sys.path:
    sys.path.insert(0, str(ROOT_DIR))

from modules.utils import (
    get_dashboard_summary,
    render_module_card,
    render_status_badge,
)


st.title("Payroll Process Automation Suite")
st.caption("Enterprise Payroll Automation Platform")

st.markdown(
    """
    Centralized automation platform for payroll processing, report generation,
    validation, reconciliation, and audit-ready output management.
    """
)

summary = get_dashboard_summary()

metric_1, metric_2, metric_3, metric_4 = st.columns(4)

with metric_1:
    st.metric(
        label="Reports Generated",
        value=summary["reports_generated"],
        help="Total employee reports generated by the system.",
    )

with metric_2:
    st.metric(
        label="Employees Processed",
        value=summary["employees_processed"],
        help="Total employee UANs processed across all modules.",
    )

with metric_3:
    st.metric(
        label="Successful Executions",
        value=summary["successful_executions"],
        help="Total successful module executions.",
    )

with metric_4:
    st.metric(
        label="Processing Time Saved",
        value=summary["processing_time_saved"],
        help="Estimated manual effort saved through automation.",
    )

st.divider()

st.subheader("Automation Modules")

left_column, right_column = st.columns(2)

with left_column:
    render_module_card(
        title="Payroll Report Generation",
        description=(
            "Generate employee-wise payroll reports from raw EPFO wage files "
            "and Higher Pension master data."
        ),
        status="In Progress",
        page_path="pages/Payroll_Report_Generation.py",
        cta_label="Open Module",
        icon="📄",
    )

with right_column:
    render_module_card(
        title="Payroll Validation & Reconciliation",
        description=(
            "Validate processed payroll reports, reconcile EPFO data, update "
            "arrears, and generate final audit-ready reports."
        ),
        status="In Progress",
        page_path="pages/Payroll_Validation.py",
        cta_label="Open Module",
        icon="✅",
    )

st.divider()

st.subheader("Overall Workflow")

st.markdown(
    """
    **Raw Wage Files**  
    → **Module 1: Payroll Report Generator**  
    → **Employee Reports**  
    → **Module 2: Payroll Validation & Reconciliation**  
    → **Final Payroll Reports**
    """
)

st.divider()

st.subheader("Future Modules")

future_modules = [
    {
        "name": "Module 3 — UAN Contact Extractor",
        "description": (
            "Extract employee mobile numbers and email IDs from the EPFO portal "
            "using Playwright automation."
        ),
        "status": "Coming Soon",
    },
    {
        "name": "Module 4 — SAP Payroll Reconciliation",
        "description": (
            "Reconcile payroll data between SAP and EPFO systems and generate "
            "compliance reports."
        ),
        "status": "Coming Soon",
    },
    {
        "name": "Module 5 — Payroll Analytics Dashboard",
        "description": (
            "Interactive dashboards showing payroll trends, wage revisions, "
            "arrears, reconciliation summaries, and processing statistics."
        ),
        "status": "Coming Soon",
    },
]

for future_module in future_modules:
    with st.container(border=True):
        column_left, column_right = st.columns([5, 1])

        with column_left:
            st.markdown(f"**{future_module['name']}**")
            st.caption(future_module["description"])

        with column_right:
            render_status_badge(future_module["status"])